services:
  
  fluentd:
    build: .
    ports:
      - 9880:9880
    env_file: 
      - .env
    volumes:
      - ./application_default_credentials.json:/etc/google/auth/application_default_credentials.json

  fluent-bit:
    image: fluent/fluent-bit
    env_file: 
      - .env
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
